export const quotes: string[] = [
    "Reading is dreaming with open eyes.",
    "A reader lives a thousand lives before he dies.",
    "Books are a uniquely portable magic.",
    "The only thing you absolutely have to know is the location of the library.",
    "A room without books is like a body without a soul.",
    "We lose ourselves in books, we find ourselves there too.",
    "I can do this all day.",
    "Part of the journey is the end.",
    "With great power comes great responsibility.",
    "I am Iron Man.",
    "On your left",
    "Way to go tic-tac",
    "Dormammu, I've come to bargain.",
    "You can't control the wind, but you can adjust your sale",
    "If you are a lover, you have to be a fighter",
    "I'm not the whisky you want... I'm the water you need",
    "You merely adopted the dark, but i was born in it",
    "Why so serious?",
    "You either die a hero or live long enough to see yourself become the villain.",
    "It's not who I am underneath, but what I do that defines me.",
    " I'm vengeance.",
    "The world only makes sense if you force it to.",
    "Do not go gentle into that good night.",
    "You mustn't be afraid to dream a little bigger, darling.",
    "A man's got to have a code.",
    "Time is the only true unit of measure.",
    "Are you watching closely?",
    "Exercise? I thought you said 'extra fries.'",
    "Some people graduate with honors, I am just honored to graduate.",
    "If at first you don't succeed, skydiving is not for you.",
    "Common sense is like deodorant. The people who need it most never use it.",
    "Don't worry if plan A doesn't work, there are 25 more letters in the alphabet.",
    "Success is not final, failure is not fatal: it is the courage to continue that counts.",
    "Hard work beats talent when talent doesn't work hard.",
    "Believe you can and you're halfway there.",
    "It's not whether you get knocked down, it's whether you get up.",
    "Your time is limited, so don't waste it living someone else's life.",
    "It does not do to dwell on dreams and forget to live.",
    "Happiness can be found even in the darkest of times, if one only remembers to turn on the light.",
    "I solemnly swear that I am up to no good.",
    "Mischief managed.",
    "Do. Or do not. There is no try.",
    "May the Force be with you.",
    "There is no spoon.",
    "Roads? Where we're going, we don't need roads.",
    "Life is like a box of chocolates. You never know what you're gonna get.",
    "I'm gonna make him an offer he can't refuse.",
    "Not all those who wander are lost.",
    "Keep calm and carry on.",
    "To infinity and beyond!",
    "Get busy living, or get busy dying.",
    "Carpe diem. Seize the day, boys.",
    "It's not the years, honey, it's the mileage.",
    "Expecto Patronum.",
    "Keep your friends close, but your enemies closer.",
    "After all, to the well-organized mind, death is but the next great adventure.",
    "It matters not what someone is born, but what they grow to be.",
    "I am Groot.",
    "I'm always angry.",
    "I volunteer as tribute.",
    "I'm the king of the world!",
    "Just keep swimming.",
    "Why do we fall? So we can learn to pick ourselves up.",
    "Some men just want to watch the world burn.",
    "The only limit to our realization of tomorrow is our doubts of today.",
    "In the middle of every difficulty lies opportunity.",
    "Keep moving forward.",
    "You're no God... I renounce you"
  ];
  